version: '3'

services:
  postgres:
    image: postgres:13
    container_name: nestjs-db-chat-postgres-db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: pass123
      POSTGRES_DB: postgres
    volumes:
      - nestjs_postgres_db:/data/postgres
    ports:
      - 5432:5432

  pgadmin:
    image: dpage/pgadmin4
    environment:
       PGADMIN_DEFAULT_EMAIL: admin@admin.com
       PGADMIN_DEFAULT_PASSWORD: admin
       PGADMIN_LISTEN_PORT: 8080
    volumes:
      - my-data:/var/lib/pgadmin
    ports:
      - 8080:8080
    depends_on:
      - postgres
    
volumes:
  nestjs_postgres_db:
  my-data: